name: chrome_apis
version: 0.1.0
description: A library for accessing the `chrome.*` APIs available in Chrome extensions.
homepage: https://github.com/xvrh/chrome_apis
environment:
  sdk: '^3.1.0'

dev_dependencies:
  analyzer:
  build_runner:
  checks:
    git:
      url: https://github.com/dart-lang/test.git
      path: pkgs/checks
  code_builder:
  collection:
  dart_style:
  fetch_client:
  http:
  json_annotation:
  json_serializable:
  lints:
  mockito:
  path:
  petitparser:
  puppeteer:
  shelf:
  shelf_router:
  shelf_static:
  test:
  web: 0.1.4-beta
  yaml:

dependency_overrides:
  code_builder:
    git:
      url: 'https://github.com/dart-lang/code_builder.git'
  mockito:
    git:
      url: 'https://github.com/dart-lang/mockito.git'
  petitparser:
    git:
      url: https://github.com/petitparser/dart-petitparser.git