name: chrome_extension
version: 0.2.0
description: A library for accessing the `chrome.*` APIs available in Chrome extensions.
homepage: https://github.com/xvrh/chrome_extension.dart
environment:
  sdk: '^3.2.0'

dev_dependencies:
  analyzer:
  build_runner:
  checks:
    git:
      url: https://github.com/dart-lang/test.git
      path: pkgs/checks
  code_builder:
  collection:
  dart_style:
  fetch_client:
  http:
  json_annotation:
  json_serializable:
  lints:
  mockito:
  path:
  petitparser:
  process_runner:
  project_tools:
    git:
      url: https://github.com/xvrh/project_tools.dart.git
      ref: '76d200c'
  puppeteer:
  shelf:
  shelf_router:
  shelf_static:
  test:
  web: 0.3.0
  yaml:

dependency_overrides:
  mockito:
    git:
      url: 'https://github.com/dart-lang/mockito.git'
