name: Build
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    name: Run tests ${{matrix.sdk}} on ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - uses: actions/checkout@v4
      - run: dart --version
      - run: |
          (dart pub get) && \
          (cd extension_examples/dart && dart pub get) && \
          (cd extension_examples/flutter && flutter pub get)
      - run: flutter analyze --fatal-infos .
      - run: dart run puppeteer:download_chrome
      - run: xvfb-run --auto-servernum dart test
        if: runner.os == 'Linux'
      - run: dart test
        if: runner.os != 'Linux'
      - run: dart tool/gen_apis.dart
      - run: dart tool/prepare_submit.dart
      - name: "check for uncommitted changes"
        run: |
          git diff --exit-code --stat -- . \
          || (echo "##[error] found changed files after build. please run 'dart tool/prepare_submit.dart'" \
                   "and check in all changes" \
              && exit 1)
